### ISSUE TITLE
Wrong default icon?

### ISSUE THREAD

**Issue by B5r1oJ0A9G** [william-gr/freenas-bacula#2]
Not sure if this is intended but the transmission default icon is used.

**Comment by william-gr** [comment]
Do you know where I can find the bacula icon? :P

**Comment by B5r1oJ0A9G** [comment]
Yes ;-)

/usr/local/www/freenasUI/media/images/ui/tree/bacula.png

within [this](https://support.freenas.org/attachment/ticket/1419/FreeNAS-8.0.4-RELEASE-BaculaStorageDaemon-0.1.tgz) Tarball

**Comment by william-gr** [comment]
Thanks :D
