### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by mwpher** [william-gr/freenas-bacula#20]
As I use the plugin, I encounter more and more error messages (as documented in other bug reports) until it becomes completely unusable. I can't make it work even for the most basic tasks. Is the plugin owner simply too busy, or is a complete fork necessary?

I'm sorry to be 'that whiny poster', but I have no ability to fix the bugs and I get the feeling that any patches I made will not be merged anyway.

**Comment by william-gr** [comment]
Feel free to fork it, I do not use the plugin anymore and have no time to continue to work on it.

**Comment by TheGrandWazoo** [comment]
I have forked it and added some changes that I thought was needed but I have not built a pbi for it. 

If there is a need for it, I will be glad to add/fix some functionality to it. 

Python is not my strong language but I can muck through it. 

Thanks, 

Kevin Scott Adams 
KSA Technologies, LLC 
kevin.adams@ksatechnologies.com 
----- Original Message -----

**Comment by mwpher** [comment]
I think the two big issues that kept me from setting it up are #15 and #16. That'll get the plugin back to more or less working status. Then we can maybe think about adding features, like upgrading bacula to version 7. I'm not sure how much I can fix any of the javascript stuff, but I can at least test things out and do whatever I can; I'm quite eager to get this plugin working. :) I'll copy the outstanding issues and file them on [your repo](https://github.com/TheGrandWazoo/freenas-bacula), if that's ok with you.
